language: erlang

otp_release:
   - 22.0.4

before_install:
    - git clone https://github.com/erlang/rebar3.git; cd rebar3; ./bootstrap; sudo mv rebar3 /usr/local/bin/; cd ..

script:
  - make compile
  - make xref
  - make eunit
  - make ct

sudo: false